name: Actions Workflow

on: 
  push:
    branches:
      - main
      - 'feature/*'
  pull_request:
    types: [closed, opened]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run: |
          Get-ChildItem
        shell: pwsh